### ISSUE TITLE
Ошибка HTTP = ESP8266WebServer (port)

### ISSUE THREAD

**Issue by Svet98** [tretyakovsa/esp8266-arduino-programm#1]
Доброго времени суток, Сергей.
IDE 1.8.5 выдаёт ошибки при компиляции. Спасает прямое указание. Косвенное почему-то не понимает. Подозреваю, рабочий полный скетч sonoff (Ваш) по этой причине не компилируется.
Не знаю как здесь выложить "картинки", выкладываю на гугле.

Ошибка если компилировать as is
[https://drive.google.com/file/d/101VKxrgba9TIrIizVShfqVeTvmVipRMM/view?usp=sharing](url)

Если принять во внимание Ваш комментарий
[https://drive.google.com/file/d/1UklDznRjZPRgFF8GuSLCfo-aKYI6kIBJ/view?usp=sharing](url)

Если указать "прямую" а не косвенную, компилируется и работает - ESP8266WebServer (port);
[https://drive.google.com/file/d/1LDxi_nefFQDbHCEnIlQ07Ik1H4HDNMQA/view?usp=sharing](url)

**Comment by tretyakovsa** [comment]
Да, это стало так для ядра 2.4.0
Если использовать 2.3.0 все будет работать. Скетч sonoff вообще в 2.4.0 становится больше и не лезет в память так как надо. Так что я остаюсь на 2.3.0 пока.

**Comment by Svet98** [comment]
Спасибо! Сменила библиотеку и всё без ошибок скомпилировалось.
